# Generated by Django 5.1.3 on 2024-11-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=100)),
                ('activo', models.BooleanField(default=True)),
                ('nivel_de_satisfaccion', models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')])),
            ],
        ),
    ]
