# Generated by Django 5.1.3 on 2024-11-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
